# ===================================
# CONFIGURACION DE LA APLICACION
# ===================================
spring.application.name=siaa_control_asistencia

# ===================================
# CONFIGURACION DEL SERVIDOR
# ===================================
server.port=${PORT:8081}
server.servlet.context-path=/api

# ===================================
# CONFIGURACION DE MYSQL - RAILWAY
# ===================================
spring.datasource.url=jdbc:mysql://autorack.proxy.rlwy.net:20134/railway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=nXQNPagMktbnAIPLYkztGQJYpZFskHgj
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===================================
# CONFIGURACION DE JPA/HIBERNATE
# ===================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# ===================================
# CONFIGURACION DE JWT
# ===================================
app.jwt.secret=SiaaSecretKeyParaJWT2026MuySeguraYLargaDeAlMenos256BitsParaHS512
app.jwt.expiration=86400000

# ===================================
# CONFIGURACION DE CORS
# ===================================
app.cors.allowed-origins=*

# ===================================
# CONFIGURACION DE LOGGING
#